# standard jekyll configuration

permalink: /:year/:month/:day/:title/
pygments:  true
markdown: rdiscount
exclude: ['readme.md', 'Rakefile', 'config.rb', '.gitignore', '.sass-cache', 'Gemfile', 'Gemfile.lock']

title: The Praxis Network
